//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long id { get; set; }
        public long CarId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public long StatusId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
